version: '3'
services:
  flyway:
    image: flyway/flyway:8.5.12
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    environment:
      - FLYWAY_USER=deguser
      - FLYWAY_PASSWORD=degpass
      - FLYWAY_URL=jdbc:postgresql://db:5432/degdb
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=deguser
      - POSTGRES_PASSWORD=degpass
      - POSTGRES_DB=degdb
